# Generated by Django 4.1.4 on 2023-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_alter_blog_autor_alter_perfil_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
